apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testgo0103b-gitops
  description: This is GitOps manifest for testgo0103b   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testgo0103b
    backstage.io/kubernetes-id: testgo0103b 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: testgo0103b   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testgo0103b
