apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: testgo0103b
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: artifactory-artifactory-jcr.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap-docker/testgo0103b:d3890a2ac45bdd9992d35eb40727c18f6db332e2@sha256:ad693cffe842f08bdb50572dc11116ad6eda42d0a603e1f4769a91b25c0148e1
          name: container-image
